"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)ry4u6folq8q+3+^a_*3c33wol4(jnvsn74-iy(y8+$genk@l_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'autopecas-saojose.onrender.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
import os

# Onde as imagens serão salvas no seu PC
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Adicione sua "loja" na lista de APPS instaladas (procure por INSTALLED_APPS)
# Ela deve ficar assim:
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'loja',  # <--- ADICIONE ISSO AQUI
]

# Substitua o que está entre aspas pelo seu token real
MELHOR_ENVIO_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiM2Q1Y2E3NzZlYTlkNGVjODExZTRjY2IyMzNlZTRmNDdiMjhkYTM1MzY5YjQ3MGVkZWQ0YjNmYjczNjQ0OTJkOWI5M2ZkNjI4ZjI5YzgzNGYiLCJpYXQiOjE3NzE5Nzg3MDUuNTk1MDAzLCJuYmYiOjE3NzE5Nzg3MDUuNTk1MDA1LCJleHAiOjE4MDM1MTQ3MDUuNTgzODU2LCJzdWIiOiJhMTI5MTY0MS0wOTZhLTRjZjMtYTEyMC1jZjA4ZDQwOWFhNjQiLCJzY29wZXMiOlsiY2FydC1yZWFkIiwiY2FydC13cml0ZSIsImNvbXBhbmllcy1yZWFkIiwiY29tcGFuaWVzLXdyaXRlIiwiY291cG9ucy1yZWFkIiwiY291cG9ucy13cml0ZSIsIm5vdGlmaWNhdGlvbnMtcmVhZCIsIm9yZGVycy1yZWFkIiwicHJvZHVjdHMtcmVhZCIsInByb2R1Y3RzLWRlc3Ryb3kiLCJwcm9kdWN0cy13cml0ZSIsInB1cmNoYXNlcy1yZWFkIiwic2hpcHBpbmctY2FsY3VsYXRlIiwic2hpcHBpbmctY2FuY2VsIiwic2hpcHBpbmctY2hlY2tvdXQiLCJzaGlwcGluZy1jb21wYW5pZXMiLCJzaGlwcGluZy1nZW5lcmF0ZSIsInNoaXBwaW5nLXByZXZpZXciLCJzaGlwcGluZy1wcmludCIsInNoaXBwaW5nLXNoYXJlIiwic2hpcHBpbmctdHJhY2tpbmciLCJlY29tbWVyY2Utc2hpcHBpbmciLCJ0cmFuc2FjdGlvbnMtcmVhZCIsInVzZXJzLXJlYWQiLCJ1c2Vycy13cml0ZSIsIndlYmhvb2tzLXJlYWQiLCJ3ZWJob29rcy13cml0ZSIsIndlYmhvb2tzLWRlbGV0ZSIsInRkZWFsZXItd2ViaG9vayJdfQ.RDPlu8FZfzD3CO8jxnlgSXmsSCsJ8aMX24m_LnWVYBgseDuiHoCzmvF-iHKZMYlN1LvKWdfSrmFKAGmXAuM8ePfB4AxnUf-CoS7g3wbWNMIpnr3fU7oC7DNTMAB-4gRdhL3Kcs_5TlGxGc3QVxIueo5FUHu4ewCY3ueHiIQyfiqGiFczGjKE5ke7rj2nSRriTGe8BMAnI21Ex9FJs9LlH6kG-qtpricg_yqlS7i2oQZ5MuIbzi5V0OocOK95Yj1XCAqRZZtZleGpeP5swzZL_Ba9ueHgyxDkoNu8UcmAV-o2A8HmvGlt7_3lcdvogLRiC2M29sB-qcDZkSg1kSYoiR7NXmJJVtjGyh9s-Tds5sOF56bcOkuMSnf4VbAGjaiWvCw0fqRundg38WUDwmJihMO3hex1_XDO4fBGsQKIPWYPdx2SLJEmIZG-0hGtZF4qCLyszu2kfp271TtCVVuFncrjbUiCET43IFIJ6onnweEBfUVSknRO33-YPYJlgFshmmVL_LXgGax9hGSqfnz_maALZdd_CZf1PzJvUscYFc0m-9kQacjNzd79fk-ozcNuc-JVt5SPhnOFUbFYcGYrW_7aw6f7_1ZKMUQczUsKAzjsowgFCOp8nT2HLRAtfViU0b0_6mL_cZk6WTCFXVm3prgqZ2Q8xRh3A8Q6Tq08NF0"
MELHOR_ENVIO_URL = "https://www.melhorenvio.com.br/api/v2/me/shipment/calculate"
CEP_ORIGEM = "88133322"  # COLOQUE AQUI O SEU CEP (O CEP da loja)

ASAAS_API_KEY = '$aact_prod_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmNhZGIwZDAzLTNkNzUtNGNlYS1iZGM5LTg1OTBmMWVkMTNlMTo6JGFhY2hfNTE3MGYwYjYtZGVlMS00NjE5LTk3MzYtZjk2ZjUyM2ZjYzVi'
ASAAS_URL = 'https://www.asaas.com/api/v3' # URL de produção